### ISSUE TITLE
MSVD checkpoint

### ISSUE THREAD

**Issue by avinashsai** [jpthu17/DiCoSA#1]
Hi,

Congrats on your amazing work! Can you please upload the MSVD checkpoint and steps for inference?

**Comment by jpthu17** [comment]
Thank you for your attention to our work.
The code and inference steps for MSVD can be found in our work EMCL (https://github.com/jpthu17/EMCL/tree/main/video_retrieval/EMCL-Net#train-on-msvd). 
I have other things to do recently, so I will probably update this codebase in June and upload the MSVD checkpoint.

**Comment by avinashsai** [comment]
Thanks for your comment. When I run using the same MSVD dataset in ECML I get the following error:

`[2023-05-06 23:11:45,935 tvr 540 INFO]: [finish] extract text+video feature
[2023-05-06 23:11:45,964 tvr 573 INFO]: 2145 52 2145 52
[2023-05-06 23:11:45,964 tvr 577 INFO]: [start] calculate the similarity
[2023-05-06 23:11:45,964 tvr 383 INFO]: [finish] map to main gpu
[2023-05-06 23:11:45,975 tvr 397 INFO]: [finish] map to main gpu
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:26<00:00,  1.28it/s]
[2023-05-06 23:15:37,725 tvr 580 INFO]: [end] calculate the similarity
[2023-05-06 23:15:37,725 tvr 583 INFO]: [start] compute_metrics
[2023-05-06 23:15:37,725 tvr 585 INFO]: before reshape, sim matrix size: 2145 x 52
Traceback (most recent call last):
  File "main_retrieval.py", line 700, in <module>
    main()
  File "main_retrieval.py", line 663, in main
    scheduler, global_step, max_steps, val_dataloader)
  File "main_retrieval.py", line 341, in train_epoch
    R1 = eval_epoch(args, model, val_dataloader, args.device)
  File "main_retrieval.py", line 593, in eval_epoch
    t2v_sim_matrix_new = np.stack(tuple(t2v_sim_matrix_new), axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/playpen/avinashm/anaconda3/envs/frozen/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
`

**Comment by beatriceadel** [comment]
Hi, I am facing the same issue when trying to train on the MSVD dataset. I got the same errors as the message above.

**Comment by jpthu17** [comment]
> Hi, I am facing the same issue when trying to train on the MSVD dataset. I got the same errors as the message above.

I'm sorry for not replying in time. I've been busy with other DDLs. I will fix the bug as soon as possible.

**Comment by adrianofragomeni** [comment]
I have the same error when training with MSVD. Could you pleasetry to solve the bug?
