### ISSUE TITLE
i met some issue when i cry to train on the msvd dataset.

### ISSUE THREAD

**Issue by Asakinevergup** [jpthu17/DiCoSA#9]
Hi, I am facing the  issue when trying to train on the MSVD dataset. I got the errors as the message below.
command： torchrun  main_retrieval.py --do_train 1 --workers 8 --n_display 10 --epochs 20 --lr 1e-4 --coef_lr 1e-3 --batch_size 128 --batch_size_val 128 --anno_path data/MSVD/anns --video_path data/MSVD/MSVD_Videos --datatype msvd --max_words 32 --max_frames 12 --video_framerate 1 --output_dir output    
output：
[rank0]: Traceback (most recent call last):
[rank0]:   File "/DiCoSA/main_retrieval.py", line 698, in <module>
[rank0]:     main()
[rank0]:   File "/DiCoSA/main_retrieval.py", line 659, in main
[rank0]:     tr_loss, global_step = train_epoch(epoch, args, model, train_dataloader,
[rank0]:   File "DiCoSA/main_retrieval.py", line 339, in train_epoch
[rank0]:     R1 = eval_epoch(args, model, val_dataloader, args.device)
[rank0]:   File "DiCoSA/main_retrieval.py", line 604, in eval_epoch
[rank0]:     tv_metrics = compute_metrics(t2v_sim_matrix_new)
[rank0]:   File "DiCoSA/tvr/utils/metrics.py", line 12, in compute_metrics
[rank0]:     d = np.diag(-x)
[rank0]:   File ".conda/envs/DiCoSA/lib/python3.9/site-packages/numpy/lib/twodim_base.py", line 303, in diag
[rank0]:     raise ValueError("Input must be 1- or 2-d.")
[rank0]: ValueError: Input must be 1- or 2-d.
it will be appreciated if u can help me, thanks!

**Comment by adrianofragomeni** [comment]
DId you solve this problem?
